import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

const jakartaSans = Plus_Jakarta_Sans({
  variable: "--font-jakarta-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Web CRUD Nextjs Mongodb",
  description: "Generated by Muhamamd Dafa Adiwinata",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${jakartaSans.variable} antialiased`}
    >
      <body>{children}</body>
    </html>
  );
}
